### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Antoine4011** [Divi/AjaxLoginBundle#1]
When I type 

> php composer.phar update divi/ajax-login-bundle

I have the following error:

> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
> - The requested package divi/ajax-login-bundle could not be found in any version, there may be a typo in the package name.

**Comment by Divi** [comment]
Thanks for the report, just edit your composer.json with this line :

``` js
 {
     "require": {
        "divi/ajax-login-bundle": "dev-master"
     }
 }
```

(replace "*" by "dev-master")

**Comment by Antoine4011** [comment]
Thanks for the reply. Great bundle by the way. :)

Any plan to do the same for the Register action?

**Comment by Divi** [comment]
Great idea ! I'll do it soon, thanks =).
