### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by charlyox** [Divi/AjaxLoginBundle#11]
Hello there, 
I have setup this bundle and updated my config with ajax_form_login instead of form_login in my parameters.yml.

Unfortunately it doesn't work... I guess my newbieness suffers from a lack of information: The examples provided are only template-examples. I don't know what I should do in my controller. 

I'd like to have a full example vs "classical" fos-userbundle login: routing, parameters, controller, templates, JS!!! Even services if any!!!

If anybody could help I'd be grateful

Charles

**Comment by Divi** [comment]
Hello @charlyox,

Could you explain me your error please ?
You don't have to edit your controller, your only changes are security.yml & your templates.

Thanks :)

**Comment by charlyox** [comment]
Hi Divi, 

well this is a great news!! 

The error is (approximately, i'm not in front of it until this evening): "the variable csrf token is undefined in the twig template".

Thanks by advance

**Comment by Divi** [comment]
This bundle doesn't provide the user bundle. Only the way to "ajaxify" the login.

If you use **FOSUserBundle**, you must override the original login template in your app/Resources folder : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/views/Security/login.html.twig

If you use your own user provider/bundle, you must add this line in your login template and replace the right form id :
`{% include 'DiviAjaxLoginBundle:Javascript:init.html.twig' with {'form_selector': '#your_form_id'} %}`

**Comment by charlyox** [comment]
Well I actually use FOSUserBundle, and am already overriding its template (I have a user bundle overriding FOSUserBundle). So I guess I should use the second solutions. Thanks anyway.

**Comment by Divi** [comment]
The error said the variable `csrf_token` is missing. In the FOSUserBundle this variable is provided by the CSRF Provider service, check the FOSUser login controller : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/SecurityController.php#L43

**Comment by charlyox** [comment]
Good Evening Divi. 

After a small brainstorm I found out. Your bundle works just fine. The thing I missed is that I still need to call FOS 's login route. 

I want to able a popup-div for login. For this I will use your bundle, but I still need to find out how to call FOSUser's controller inside my template!

Good evening and thanks again.

Charles

**Comment by Divi** [comment]
Just call the `<form action="{{ path("fos_user_security_check") }}" method="post">` route, and the FOSUserBundle will be handled :)

**Comment by charlyox** [comment]
Must be missing something... Still the "Variable "csrf_token" does not exist" error.

in my homepage template:
{% block section1 %}
    {% if not is_granted("ROLE_CLIENT") %}
  {%  include ("OptadifUserBundle:Security:ajaxlogin.html.twig") %}
    {%  endif %}
{% endblock %}

ajaxlogin.html.twig (copy and paste of your example): 

{# Include this line to get the javascript AJAX code #}
{% include 'DiviAjaxLoginBundle:Javascript:init.html.twig' with {'form_selector': '#form-login'} %}

{# Dot not forget to set the form's id attribute #form-login and link to the line above #}

<form action="{{ path("fos_user_security_check") }}" method="post" id="form-login">
    <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
    <label for="username">{{ 'security.login.username'|trans({}, 'FOSUserBundle') }}</label>
    <input type="text" id="username" name="_username" value="{{ last_username }}" required="required" />
    <label for="password">{{ 'security.login.password'|trans({}, 'FOSUserBundle') }}</label>
    <input type="password" id="password" name="_password" required="required" />
    <input type="checkbox" id="remember_me" name="_remember_me" value="on" />
    <label for="remember_me">{{ 'security.login.remember_me'|trans({}, 'FOSUserBundle') }}</label>
    <input type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans({}, 'FOSUserBundle') }}" />
</form>

I should probably include a login controller via AJAX. I want the display of the form to be rendered with AJAX too, not only the authentication action.

I want the login action to be possible on each and every page, depending on peculiar actions. I don't want a login page. I want a login popin!!!

Thanks again

Charles

**Comment by charlyox** [comment]
strange enough, I copied paste your code but GitHub didn't take the js part. I guess you know it by heart anyway!

**Comment by charlyox** [comment]
I found the solution!
For people wanting to have an ajax rendering of the login form (like a popup for example):
call it via an ajax script on the page you want it to be displayed. 

<div id="popinlogin"></div>

<script type="text/javascript">
    $.ajax({
        url: "{{ path('fos_user_security_login') }}",
        type: 'POST',
        success: function (data) {
            if (data.has_error) {
                // Insert your error process
                alert(data.error);
            }
            else {
                $('#popinlogin').html(data);
            }
        }
     });

Thanks a lot Divi.

Charles

**Comment by Divi** [comment]
Thanks for the solution @charlyox :+1:
