### ISSUE TITLE
How can we get the translations for the error message?

### ISSUE THREAD

**Issue by Monomachus** [Divi/AjaxLoginBundle#2]
Hello,

Great bundle !
But in our case we also need the error message to appear in french, how can we achieve this without modifying the bundle?

For example "Bad credentials" should have been translated in french if we used the translations from FOS (\FOS\UserBundle\Resources\translations\FOSUserBundle.fr.yml).

Thank you.

**Comment by Divi** [comment]
It will be done soon, be patient =)
If you want to do by your own, you must use the translator service in the AjaxAuthenticationFailureHandler::onAuthenticationFailure().

**Comment by Divi** [comment]
Hey @Monomachus,

Sorry for the wait. The translation has been implemented today !

Thanks

**Comment by Monomachus** [comment]
Very cool. Let me check it. And thank you.
