### ISSUE TITLE
Override

### ISSUE THREAD

**Issue by meandus** [Divi/AjaxLoginBundle#4]
When you are using FOSUserBundle and you want to use Divi/AjaxLoginBundle
Could you explain how to override the template to remove alert(data.error);

my own SecurityController extends already FOSUserBundle.

**Comment by Divi** [comment]
Hey @meandus,

You can easily create a new template based on "Javascript/init.html.twig".
It was just an exemple, and isn't good for production, javascript alerts are ugly.

Simply create your template, copy/paste the code from "Javascript/init.html.twig" and include it in your view :

``` twig
{% include 'Foo:Bar:init.html.twig' with {'form_selector': '#your-form'} %}
```
