### ISSUE TITLE
Psr\Log\LoggerInterface, instance of Symfony\Bridge\Monolog\Logger

### ISSUE THREAD

**Issue by gecatalin** [Divi/AjaxLoginBundle#6]
So i tried to override the handlers and i got the following error 

Catchable Fatal Error: Argument 4 passed to Sn\ApiBundle\Security\Http\Authentication\AjaxAuthenticationFailureHandler::__construct() must be an instance of Psr\Log\LoggerInterface, instance of Symfony\Bridge\Monolog\Logger given, called in /var/www/app/cache/dev/appDevDebugProjectContainer.php on line 2721 and defined in /var/www/src/Sn/ApiBundle/Security/Http/Authentication/AjaxAuthenticationFailureHandler.php line 31

I run php 5.5 and as i heard this might be the problem.

**Comment by Divi** [comment]
Hey @gecatalin,

Can you paste your AjaxAuthenticationFailureHandler code please ? (pastebin or gist)

I'll check this issue this week =)

**Comment by Divi** [comment]
Hey @gecatalin,

Works with Symfony v2.3.x and v2.4.x.
Show me your code, and i'll help you.

**Comment by Divi** [comment]
Hey @gecatalin,

I saw you use Symfony version 2.0 or 2.1.
I created new branch for these versions : https://github.com/Divi/AjaxLoginBundle/tree/2.0-2.1
